name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check sync
      run: cargo check --verbose --features sync
    - name: Check async
      run: cargo check --verbose --features tokio-runtime
    - name: Formatting
      run: cargo fmt -- --check
    - name: Run tests sync
      run: cargo test --verbose --features sync
    - name: Run tests async
      run: cargo test --verbose --features tokio-runtime
